name: 'Linux'

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  schedule:
    - cron: "0 6 * * *"

jobs:
  linux-build-and-test-stable:
    uses: './.github/workflows/01-build-and-test-unix.yml'
    with:
      os: 'ubuntu-latest'
      toolchain: 'stable'

  linux-build-and-test-beta:
    uses: './.github/workflows/01-build-and-test-unix.yml'
    with:
      os: 'ubuntu-latest'
      toolchain: 'beta'

  linux-build-and-test-msrv:
    uses: './.github/workflows/01-build-and-test-unix.yml'
    with:
      os: 'ubuntu-latest'
      toolchain: '1.63'
      msrv: true

  # Nightly check is performed on ubuntu only.
  linux-build-and-test-nightly:
    uses: './.github/workflows/01-build-and-test-unix.yml'
    with:
      os: 'ubuntu-latest'
      toolchain: 'nightly'

  linux-coverage-stable:
    uses: './.github/workflows/02-coverage.yml'
    with:
      os: 'ubuntu-latest'

  linux-lint-stable:
    uses: './.github/workflows/03-lint.yml'
    with:
      os: 'ubuntu-latest'
