name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_VERBOSE: true
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        toolchain: ["1.40.0", "1.45.0", stable, beta]
        profile: ['', --release]
        features: ['', '--features full']
        exclude:
          - os: windows-latest
            features: '--features full'
          # Tokio 1.0 (and this capture-stream) requires 1.45
          - toolchain: "1.45.0"
            features: '--features full'
          - toolchain: "1.40.0"
            features: ''
        include:
          # nightly check is performed on ubuntu only.
          - os: ubuntu-latest
            toolchain: nightly
            profile: ''
            features: --features full 
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install libpcap (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libpcap-dev
      - name: Install libpcap (macos)
        if: matrix.os == 'macos-latest'
        run: brew install libpcap
      - name: Install WinPcap and WinPcap 4.1.2 Developer's Pack (windows)
        if: matrix.os == 'windows-latest'
        run: |
          cinst -y winpcap --version 4.1.3.20161116
          (New-Object System.Net.WebClient).DownloadFile("https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip", "C:/WpdPack.zip")
          Expand-Archive -LiteralPath C:/WpdPack.zip -DestinationPath C:/
          echo "LIB=C:/WpdPack/Lib/x64" >> $env:GITHUB_ENV
      - name: Select rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
          override: true
      - name: cargo build
        run: cargo build ${{ matrix.profile }} ${{ matrix.features }}
      - name: cargo test
        run: cargo test ${{ matrix.profile }} ${{ matrix.features }}
      - name: cargo clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy ${{ matrix.profile }} ${{ matrix.features }} -- -D warnings
      - name: cargo doc
        run: cargo doc ${{ matrix.profile }} ${{ matrix.features }}
      - name: cargo fmt
        if: matrix.toolchain == 'stable'
        run: cargo fmt -- --check
