name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_VERBOSE: true
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        profile: ['', --release]
        toolchain: [stable]
        features: ['', '--features full']
        exclude:
          - os: windows-latest
            features: '--features full'
        include:
          # beta and nightly checks are performed on ubuntu only.
          - os: ubuntu-latest
            profile: --release
            toolchain: beta
            features: --features full 
          - os: ubuntu-latest
            profile: ''
            toolchain: nightly
            features: --features full 
    runs-on: ${{ matrix.os }} 

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install libpcap (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libpcap-dev
      - name: Install libpcap (macos)
        if: matrix.os == 'macos-latest'
        run: brew install libpcap
      - name: Install WinPcap and WinPcap 4.1.2 Developer's Pack (windows)
        if: matrix.os == 'windows-latest'
        run: |
          cinst -y winpcap --version 4.1.3.20161116
          (New-Object System.Net.WebClient).DownloadFile("https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip", "C:/WpdPack.zip")
          Expand-Archive -LiteralPath C:/WpdPack.zip -DestinationPath C:/
          echo "::set-env name=LIB::C:/WpdPack/Lib/x64"
      - name: Select rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
          override: true
      - name: cargo test
        run: cargo test ${{ matrix.profile }} ${{ matrix.features }}
      - name: cargo clippy
        run: cargo clippy ${{ matrix.profile }} ${{ matrix.features }} -- -D warnings
